### ISSUE TITLE
Referenced scripts but with insecure connection

### ISSUE THREAD

**Issue by deleterium** [markszabo/PostQ#11]
Hi!

Some scripts are reference with insecure connection (http form, not https) in file index.html. In order to use PostQ in a secure connection, these references must be changed to secure links.

I would recommend to save this scripts also in the "external" folder, so all files will be in the same server.
Other alternative is to add a hash in <script> tag, to ensure their content is the same.

**Comment by markszabo** [comment]
Good catch. Saving them to the external folder would probably be the best solution IMHO, but having them load via https and have the hashes in the script tag to protect from the external sites being compromised could also work.

**Comment by deleterium** [comment]
To solve this (my branch deleterium.info) I put files in external folder. The problem was with webrtc, because the script calls another files. My computer does not have webcam and I was not sure if that connection was encrypted. So I decided to remove this feature in my repository, because I can not give proper support for the modifications I've done. If you want, I can make a PR with this and another bugs solved, but removed webcam support. You can check all my mods live in https://deleterium.info/chat/ (now open for tests, so no need mail registration and you can create many usernames)

**Comment by markszabo** [comment]
Sorry for the late reply. I updated the [README](https://github.com/markszabo/PostQ/blob/master/README.md) with this info and a link to your fork, so that others can take a look at that as well. Unfortunately I don't have time to move your fixes back here and test it properly, so this is all I can do now.
